### ISSUE TITLE
[fontc] --emit-ir=false leads to TasksFailed([(Be(Font), "IO failure")])

### ISSUE THREAD

**Issue by anthrotype** [googlefonts/fontmake-rs#224]
fontc has an --emit-ir flag which is true by default, however it doesn't seem to be possible to disable it.
I tried --no-emit-r or --emit-ir=false but didn't work. Passing `--emit-ir` does nothing different than not passing one at all, since the default is already true.

Should the default be false maybe? Or maybe it can be true but use clap's ArgAction::SetFalse?

**Comment by anthrotype** [comment]
If I set the default_value = false, then I get another error:

```
$ cargo run -p fontc -- --source resources/testdata/static.designspace
    Finished dev [unoptimized + debuginfo] target(s) in 0.13s
     Running `target/debug/fontc --emit-ir --source resources/testdata/static.designspace`
2023-03-30T16:30:52.628124Z: ThreadId(1): ERROR: Be(Font) failed Be(IoError(Os { code: 2, kind: NotFound, message: "No such file or directory" }))
Error: TasksFailed([(Be(Font), "IO failure")])
```

**Comment by rsheeter** [comment]
https://stackoverflow.com/questions/60458705/how-do-i-specify-a-boolean-command-line-flag-using-clap seems to support the theory bools need to default false and then get turned on by flag. That's annoying because Google best practice is to avoid negative flags but this seemingly leads you directly there, e.g. we would make the arg no_ir, default false, if you pass it we don't emit ir.

**Comment by anthrotype** [comment]
keeping open until we fix the `TasksFailed([(Be(Font), "IO failure")])` error that is uncovered by using `--emit-ir=false` (see https://github.com/googlefonts/fontmake-rs/issues/224#issuecomment-1490597862)
